FROM sbtscala/scala-sbt:eclipse-temurin-focal-11.0.21_9_1.9.8_3.3.1 as sources
COPY . /app
WORKDIR /app/
RUN sbt web/test web/clean web/dist
RUN apt update && apt install unzip
RUN mkdir /app/dist && unzip /app/web/target/universal/*.zip -d /app/dist

FROM eclipse-temurin:11.0.21_9-jre-jammy
WORKDIR /app/
COPY --from=sources /app/dist /app/
EXPOSE 9000
CMD ["/app/web-1.0-SNAPSHOT/bin/web", "-Dconfig.file=/config/application.conf"]
