FROM sbtscala/scala-sbt:eclipse-temurin-21.0.5_11_1.10.7_3.6.2  as sources
COPY . /app
WORKDIR /app/
RUN sbt akkaLoader/assembly

FROM eclipse-temurin:21-jre-ubi9-minimal
WORKDIR /app/
COPY --from=sources /app/akka-loader/target/scala-3.7.3/akka-loader-assembly-0.1.jar /app/
ENTRYPOINT ["timeout", "4h", "java", "-Xmx6096m", "-Xms256m", "-jar", "/app/akka-loader-assembly-0.1.jar"]
