package httpflows

import chpp.matchesarchive.MatchesArchiveRequest
import chpp.matchesarchive.models.MatchesArchive

object MatchesArchiveHttpFlow extends AbstractHttpFlow[MatchesArchiveRequest, MatchesArchive]
