---
- name: install pip
  become: true
  apt:
    name: python3-pip
    state: present

- name: install python docker
  pip:
    name: docker

- name: install jq
  become: true
  apt:
    name: jq
    state: present