---
- name: start docker
  community.docker.docker_container:
    name: clickhouse-server-hattrick
    image: clickhouse/clickhouse-server:23.11.3.23
    restart_policy: always
    volumes:
      - "{{ base_project_directory }}/clickhouse/volume:/var/lib/clickhouse"
      - "{{ base_project_directory }}/clickhouse/users.xml:/etc/clickhouse-server/users.xml"
      - "{{ base_project_directory }}/clickhouse/config.xml:/etc/clickhouse-server/config.xml"
      - "{{ base_project_directory }}/clickhouse/config.d/z_log_disable.xml:/etc/clickhouse-server/config.d/z_log_disable.xml"
    ulimits:
      - nofile:262144:262144
    ports:
      - 8123:8123
    state: started
