---
# tasks file for install-docker-clickhouse
  - import_tasks: 00-python-dependencies.yml

  - import_tasks: 01-copy-configs.yml

  - import_tasks: 02-docker.yml

  - import_tasks: 03-grants.yml

  - import_tasks: 04-cron-local-backup.yml
    tags:
     - cron
     - backup

  - import_tasks: 05-cron-onedrive.yml
    tags:
     - cron
     - remote-cron
     - backup
