package chpp.players.models

object MatchRoleId extends Enumeration {
  val Keeper = Value("100")
  val RIGHT_BACK = Value("101")
  val RIGHT_CENTRAL_DEFENDER = Value("102")
  val MIDDLE_CENTRAL_DEFENDER = Value("103")
  val LEFT_CENTRAL_DEFENDER = Value("104")
  val LEFT_BACK = Value("105")
  val RIGHT_WINGER = Value("106")
  val RIGHT_INNER_MIDFIELD = Value("107")
  val MIDDLE_INNER_MIDFIELD = Value("108")
  val LEFT_INNER_MIDFIELD = Value("109")
  val LEFT_WINGER = Value("110")
  val RIGHT_FORWARD = Value("111")
  val MIDDLE_FORWARD = Value("112")
  val LEFT_FORWARD = Value("113")
  val SUBSTITUTION_KEEPER = Value("114")
  val SUBSTITUTION_DEFENDER = Value("115")
  val SUBSTITUTION_INNER_MIDFIELD = Value("116")
  val SUBSTITUTION_WINGER = Value("117")
  val SUBSTITUTION_FORWARD = Value("118")
  //Not present in documentation
  val ADDITIONAL_SLOT = Value("119")
  //TODO same value
  val SUBSTITUTION_KEEPER_2 = Value("200")
  val SUBSTITUTION_CENTRAL_DEFENDER = Value("201")
  val SUBSTITUTION_WING_BACK = Value("202")
  val SUBSTITUTION_INNER_MIDFIELDER = Value("203")
  //TODO same value
  val SUBSTITUTION_FORWARD_2 = Value("204")
  //TODO same value
  val SUBSTITUTION_WINGER_2 = Value("205")
  val SUBSTITUTION_EXTRA = Value("206")
  val BACKUP_KEEPER = Value("207")
  val BACKUP_CENTRAL_DEFENDER = Value("208")
  val BACKUP_WING_BACK = Value("209")
  val BACKUP_INNER_MIDFIELDER = Value("210")
  val BACKUP_FORWARD = Value("211")
  val BACKUP_WINGER = Value("212")
  val BACKUP_EXTRA = Value("213")
  val SET_PIECES = Value("17")
  val CAPTAIN = Value("18")
  val REPLACED_PLAYER_1 = Value("19")
  val REPLACED_PLAYER_2 = Value("20")
  val REPLACED_PLAYER_3 = Value("21")
  val PENALTY__AKER_1 = Value("22")
  val PENALTY_TAKER_2 = Value("23")
  val PENALTY_TAKER_3 = Value("24")
  val PENALTY_TAKER_4 = Value("25")
  val PENALTY_TAKER_5 = Value("26")
  val PENALTY_TAKER_6 = Value("27")
  val PENALTY_TAKER_7 = Value("28")
  val PENALTY_TAKER_8 = Value("29")
  val PENALTY_TAKER_9 = Value("30")
  val PENALTY_TAKER_10 = Value("31")
  val PENALTY_TAKER_11 = Value("32")
}
