api:
  threads: 12
  customerKey:
  customerSecret:
  accessToken:
  accessTokenSecret:

spring:
  datasource:
    url:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver

clickhouse:
  databaseName:
  batchSize:
    match:
    players:

web:
  url: /loader/leagueRound

telegram:
  botToken:
  chatId:
  socksHost:
  socksPort: