---
 - name: Add Grafana repository key
   become: true
   ansible.builtin.apt_key:
     url: https://packages.grafana.com/gpg.key
     state: present

 - name: Add Grafana repository
   become: true
   ansible.builtin.apt_repository:
     repo: deb https://packages.grafana.com/enterprise/deb stable main
     state: present
     validate_certs: no

 - name: Install Grafana
   become: true
   apt:
     name: grafana
     state: present 

     #grafana.ini is not enogh :( https://stackoverflow.com/questions/28303978/changing-grafana-port
 - name: configure grafana
   become: true
   template:
     src: grafana.ini.j2
     dest: /etc/grafana/grafana.ini
     owner: root
     group: grafana

 - name: Grafana server enabled and started
   become: true
   ansible.builtin.systemd:
     state: restarted
     enabled: yes
     name: grafana-server


 - name: Install Clickhouse Grafana Plugin
   become: true
   ansible.builtin.shell:
     cmd: grafana-cli plugins install vertamedia-clickhouse-datasource 