---
 - name: .env for front
   template:
      src: .env.j2
      dest: "{{ base_project_directory }}/hat-all-stats/front/.env"
  
 - name: npm install for front
   shell:
     chdir: "{{ base_project_directory }}/hat-all-stats/front"
     cmd: npm install
   tags:
    - rebuild

 - name: build front with npm
   shell:
     chdir: "{{ base_project_directory }}/hat-all-stats/front"
     cmd: NODE_OPTIONS="--max-old-space-size=4096" npm run build
   tags:
    - rebuild

 - name: copy unit for front
   become: true
   template:
     src: hattid-front.service.j2
     dest: /etc/systemd/system/hattid-front.service

 - name: systemd unit for front
   become: true
   systemd:
     name: hattid-front
     daemon-reload: yes
     enabled: yes
     state: restarted