---
 - import_tasks: 01-web.yml
   tags: 
    - web
  
 - import_tasks: 02-front.yml
   tags: 
    - front

 - import_tasks: 03-loader.yml
   tags:
    - loader

 - import_tasks: 04-akka-loader.yml
   tags:
    - akka-loader

 - import_tasks: 05-hattrick-tests.yml
   tags:
    - tests
